### ISSUE TITLE
RecordNameStrategy and TopicRecordNameStrategy should not have suffix.

### ISSUE THREAD

**Issue by takaomag** [saabeilin/kafkian#7]
According to the following java code,
https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/TopicNameStrategy.java

https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/RecordNameStrategy.java

https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/subject/TopicRecordNameStrategy.java

I think,
- in case of `RecordNameStrategy`, a subject must be the `<fully-qulified avro recordName>`.
- in case of  `TopicRecordNameStrategy`, a subject must be the `<topicName>`-`<fully-qulified avro recordName>`.

But,
https://github.com/saabeilin/kafkian/blob/master/kafkian/serde/serialization.py#L48
all strategy has `-key` or `-value` suffix (`subject += '-key' if is_key else '-value'`). These suffix should be applied only on TopicNameStrategy.

Anyway, I feel confluent-kafka-python is not user-friendly and does not support Subject Name Strategy well.
Thank you for your nice library!

**Comment by saabeilin** [comment]
Thanks a lot @takaomag - you are absolutely right. I'll try to fix it asap (or you are welcome to submit a pull request)

**Comment by takaomag** [comment]
Thank you so much for your quick commit!
